#
# This is a hello world HOT template just defining a single compute
# server.
#
heat_template_version: 2014-10-16

description:
  Hello world HOT template that just defines a single server.
  Contains just base features to verify base HOT support.
parameters:
  image:
    type: string
    description: Image ID or image name to use for the server
    default: xenial-server-cloudimg-amd64-disk1
    constraints:
      - custom_constraint: glance.image
  key_name:
    type: string
    description: Name of an existing key pair to use for the server
    default: cle3
  flavor:
    type: string
    description: Flavor for the server to be created
    default: 2048-10-1-1
    constraints:
      - custom_constraint: nova.flavor
  private_net:
    type: string
    description: The network to which the server should be connected
    default: switch1-nat
    constraints:
      - {custom_constraint: neutron.network}

resources:
  server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      networks:
        - network: { get_param: private_net}
      user_data_format: RAW
      user_data: |
            #!/bin/bash
            sudo apt-get update
            sudo apt-get install python-minimal -y
            wget https://raw.githubusercontent.com/houssemmh/INF8480-TP3/master/server.py
            python server.py 

outputs:
  server_networks:
    description: The networks of the deployed server
    value: { get_attr: [server, networks] }
